# Music Data Preparation 

*by MaÃ«lys Boudier*

In [1]:
# import pandas package to manipulate dataframes
import pandas as pd

# initialize path to DATA folder
path_init = "/Users/maelys/Desktop/BUSA 400/Github Upload/DATA"

## Read Data
### I. EchoNest
Type of Data File: TXT

* Taste Profile User
* Train Triplets

In [2]:
# Taste profile User
# The read_csv technique DOES NOT work: Error Tokenizing Data 

import csv

# file path and name for the taste profile user data
file_echo = '/EchoNest/taste_profile_usercat_120k.txt'

# reading the txt file through a csv file reader
taste_txt = open(path_init+file_echo,'rt')
reader = csv.reader(taste_txt)

# once contents are available, put them in a list
csv_list = []
for row in reader:
    # create temporary list and reformat for consistency 
    # remove beginning "### " and remove middle arrow " --> "
    temp_row = row[0].strip("# ").split(" --> ")
    # append to main list
    csv_list.append(temp_row)
taste_txt.close()

# convert list to pandas df (iloc to remove the extra None column at the end)
taste_profile = pd.DataFrame(csv_list, columns = ["Catalog Name", "Catalog ID", "None"]).iloc[:, :-1]
taste_profile.tail()

                                             Catalog Name          Catalog ID
119292  c42edc4a151caa46924d315ecb2dcaa0296de57c_tmp_c...  CADFBDG133329DCAD8
119293  710463dc7436180bfcee156281f9cb69704200af_tmp_c...  CAVIABK133338A4A32
119294  fc8d873232dca95f428b253f8533dd75a5ceaaaa_tmp_c...  CALMZCS133338A52A9
119295  48952283c18c3f9b69a6d8daaf814c429a6deb16_tmp_c...  CAJZJQK133329DD1CF
119296  15a58fd461f71abb88d59566af16457c4e1f7be1_tmp_c...  CAHNBBG133329DD905

In [3]:
# Train Triplets 
train_triplets = pd.read_csv(path_init + '/EchoNest/train_triplets.txt', sep = "\t", header =None, names=["User ID", "Song ID", "Play Count"])
train_triplets.head()

                                    User ID             Song ID  Play Count
0  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOAKIMP12A8C130995           1
1  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOAPDEY12A81C210A9           1
2  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOBBMDR12A8C13253B           2
3  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOBFNSP12AF72A0E22           1
4  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOBFOVM12A58A7D494           1

### II. MLHD Last.fm
Type of Data File: CSV

* Behavioural Features
* Activity: different time units

In [11]:
# open activity by days of the week (because smallest file)

activity_day_week = pd.read_csv(path_init + "/MLHD Lastfm/Activity/MLHD_perc_per_day_of_the_week.csv", sep = "\t")
activity_day_week.head()

,uuid,M,T,W,R,F,S,X
0,dfb7ea9d-6e4f-48e4-96f6-59abcc207d55,0.174581,0.164352,0.186547,0.179438,0.149946,0.080264,0.064873
1,a89cb9c5-ba84-424e-8950-16657bb6f7af,0.143616,0.159441,0.158584,0.147783,0.156190,0.123843,0.110544
2,dde6c339-c256-43f1-94e8-02f4043abdf9,0.163986,0.142545,0.134701,0.135143,0.132586,0.147831,0.143208
3,44d70878-6e9a-432f-831d-179e8354f448,0.127730,0.123191,0.143868,0.120121,0.141105,0.167601,0.176384
4,e553ab79-5e93-48fc-aa63-1c4319cafd23,0.177713,0.145637,0.163741,0.171557,0.180609,0.098759,0.061985

In [12]:
# open behavioural features
behavioural_ft = pd.read_csv(path_init + "/MLHD Lastfm/MLHD_behavioural_features.csv", sep = "\t")
                             
behavioural_ft.head()

,uuid,exploratoryness_artist,exploratoryness_album,exploratoryness_track,mainstreamness_artist,mainstreamness_album,mainstreamness_track,genderedness_artist,genderedness_album,genderedness_track,fringeness_artist,fringeness_album,fringeness_track
0,dfb7ea9d-6e4f-48e4-96f6-59abcc207d55,0.963757,0.973318,0.993622,0.053435,0.006834,0.001015,-0.007852,-0.051894,-0.000223,0.044531,0.305007,0.164938
1,a89cb9c5-ba84-424e-8950-16657bb6f7af,0.975727,0.991706,0.998850,0.032591,0.002332,0.000295,0.008674,-0.023417,0.000077,0.057260,0.172970,0.099496
2,dde6c339-c256-43f1-94e8-02f4043abdf9,0.841347,0.920057,0.985308,0.076556,0.005797,0.000824,0.033450,-0.047393,0.000298,0.017065,0.172298,0.090022
3,44d70878-6e9a-432f-831d-179e8354f448,0.939690,0.944687,0.982072,0.046826,0.005068,0.000854,0.003506,-0.038450,-0.000072,0.060308,0.380346,0.258543
4,e553ab79-5e93-48fc-aa63-1c4319cafd23,0.956886,0.965266,0.994294,0.074928,0.007073,0.001064,0.002857,-0.065306,-0.000101,0.066298,0.383351,0.190572

### III. Spotify AI Crowd
Type of Data File: CSV

* Training Set: Spotify Session 
* Track Features

In [13]:
# open training set: log mini
spotify_training = pd.read_csv(path_init + "/Spotify_AIcrowd_Training_Set_And_Track_Features_Mini/training_set/log_mini.csv")
spotify_training.head()

,session_id,session_position,session_length,track_id_clean,skip_1,skip_2,skip_3,not_skipped,context_switch,no_pause_before_play,...,long_pause_before_play,hist_user_behavior_n_seekfwd,hist_user_behavior_n_seekback,hist_user_behavior_is_shuffle,hour_of_day,date,premium,context_type,hist_user_behavior_reason_start,hist_user_behavior_reason_end
0,0_00006f66-33e5-4de7-a324-2d18e439fc1e,1,20,t_0479f24c-27d2-46d6-a00c-7ec928f2b539,False,False,False,True,0,0,...,0,0,0,True,16,2018-07-15,True,editorial_playlist,trackdone,trackdone
1,0_00006f66-33e5-4de7-a324-2d18e439fc1e,2,20,t_9099cd7b-c238-47b7-9381-f23f2c1d1043,False,False,False,True,0,1,...,0,0,0,True,16,2018-07-15,True,editorial_playlist,trackdone,trackdone
2,0_00006f66-33e5-4de7-a324-2d18e439fc1e,3,20,t_fc5df5ba-5396-49a7-8b29-35d0d28249e0,False,False,False,True,0,1,...,0,0,0,True,16,2018-07-15,True,editorial_playlist,trackdone,trackdone
3,0_00006f66-33e5-4de7-a324-2d18e439fc1e,4,20,t_23cff8d6-d874-4b20-83dc-94e450e8aa20,False,False,False,True,0,1,...,0,0,0,True,16,2018-07-15,True,editorial_playlist,trackdone,trackdone
4,0_00006f66-33e5-4de7-a324-2d18e439fc1e,5,20,t_64f3743c-f624-46bb-a579-0f3f9a07a123,False,False,False,True,0,1,...,0,0,0,True,16,2018-07-15,True,editorial_playlist,trackdone,trackdone

In [14]:
# open tf: track features
spotify_tracks = pd.read_csv(path_init + "/Spotify_AIcrowd_Training_Set_And_Track_Features_Mini/track_features/tf_mini.csv")
spotify_tracks.head()

,track_id,duration,release_year,us_popularity_estimate,acousticness,beat_strength,bounciness,danceability,dyn_range_mean,energy,...,time_signature,valence,acoustic_vector_0,acoustic_vector_1,acoustic_vector_2,acoustic_vector_3,acoustic_vector_4,acoustic_vector_5,acoustic_vector_6,acoustic_vector_7
0,t_a540e552-16d4-42f8-a185-232bd650ea7d,109.706673,1950,99.975414,0.458040,0.519497,0.504949,0.399767,7.511880,0.817709,...,4,0.935512,-0.033284,-0.411896,-0.028580,0.349438,0.832467,-0.213871,-0.299464,-0.675907
1,t_67965da0-132b-4b1e-8a69-0ef99b32287c,187.693329,1950,99.969430,0.916272,0.419223,0.545530,0.491235,9.098376,0.154258,...,3,0.359675,0.145703,-0.850372,0.123860,0.746904,0.371803,-0.420558,-0.213120,-0.525795
2,t_0614ecd3-a7d5-40a1-816e-156d5872a467,160.839996,1951,99.602549,0.812884,0.425890,0.508280,0.491625,8.368670,0.358813,...,4,0.726769,0.021720,-0.743634,0.333247,0.568447,0.411094,-0.187749,-0.387599,-0.433496
3,t_070a63a0-744a-434e-9913-a97b02926a29,175.399994,1951,99.665018,0.396854,0.400934,0.359990,0.552227,5.967346,0.514585,...,4,0.859075,0.039143,-0.267555,-0.051825,0.106173,0.614825,-0.111419,-0.265953,-0.542753
4,t_d6990e17-9c31-4b01-8559-47d9ce476df1,369.600006,1951,99.991764,0.728831,0.371328,0.335115,0.483044,5.802681,0.721442,...,4,0.562343,0.131931,-0.292523,-0.174819,-0.034422,0.717229,-0.016239,-0.392694,-0.455496

### IV. SQL lite Million Song Challenge
Type of Data File: DB (SQL Data)
https://datacarpentry.org/python-ecology-lesson/09-working-with-sql/index.html

In [15]:
import sqlite3

# Similarity Table from artist similarity (db file)

# Read sqlite query results into a pandas DataFrame
con = sqlite3.connect(path_init + "/SQLlite_MillionSong/artist_similarity.db")
similarity_df = pd.read_sql_query("SELECT * from similarity", con)

# Verify that result of SQL query is stored in the dataframe
similarity_df.head()

con.close()

In [16]:
similarity_df.describe()

                    target             similar
count              2201916             2201916
unique               44460               43578
top     ARGUACZ1187FB3F35C  AR6XZ861187FB4CECD
freq                    97                 850

In [17]:
# make networkx with all similar artists
import networkx as nx
G = nx.Graph()
G = nx.from_pandas_edgelist(similarity_df, 'target', 'similar')

In [18]:
# tracks ID
tracks = pd.read_csv(path_init + "/SQLlite_MillionSong/unique_tracks.txt", engine='python', sep = "<SEP>", header = None, names=["Track ID", "Song ID", "Artist Name", "Song Title"])
tracks.head()

             Track ID             Song ID       Artist Name         Song Title
0  TRMMMYQ128F932D901  SOQMMHC12AB0180CB8  Faster Pussy cat       Silent Night
1  TRMMMKD128F425225D  SOVFVAK12A8C1350D9  Karkkiautomaatti        Tanssi vaan
2  TRMMMRX128F93187D9  SOGTUKN12AB017F4F1    Hudson Mohawke  No One Could Ever
3  TRMMMCH128F425532C  SOBNYVR12A8C13558C       Yerba Brava      Si Vos QuerÃ©s
4  TRMMMWA128F426B589  SOHSBXH12A8C13B0DF        Der Mystic   Tangle Of Aspens

In [19]:
# artist ID
artists = pd.read_csv(path_init + "/SQLlite_MillionSong/unique_artists.txt", engine='python', sep = "<SEP>", header = None, names=["Artist ID", "Artist MBID", "Track ID", "Artist name"])
artists.head()

,Artist ID,Artist MBID,Track ID,Artist name
0,AR002UA1187B9A637D,7752a11c-9d8b-4220-ac44-e4a04cc8471d,TRMUOZE12903CDF721,The Bristols
1,AR003FB1187B994355,1dbd2d7b-64c8-46aa-9f47-ff589096d672,TRWDPFR128F93594A6,The Feds
2,AR006821187FB5192B,94fc1228-7032-4fe6-a485-e122e5fbee65,TRMZLJF128F4269EAC,Stephen Varcoe/Choir of King's College_ Cambri...
3,AR009211187B989185,9dfe78a6-6d91-454e-9b95-9d7722cbc476,TRMGURO12903CAE2F0,Carroll Thompson
4,AR009SZ1187B9A73F4,8cd574c0-b9f7-4998-94f4-654dffaecdf2,TRGWWFP12903CE7E79,Gorodisch

In [26]:
top_target_artist_id = "ARGUACZ1187FB3F35C"
top_sim_artist_id = "AR6XZ861187FB4CECD"

# find the name of the artists with top scores in similarity table
for index, row in artists.iterrows():
    if row['Artist ID'] == top_target_artist_id:
        print("TOP TARGET ARTIST:", index, row['Artist ID'], row["Artist name"])
        break
    
for index, row in artists.iterrows():
    if row['Artist ID'] == top_sim_artist_id:
        print("TOP SIMILAR ARTIST:", index, row['Artist ID'], row["Artist name"])
        break

TOP TARGET ARTIST: 19086 ARGUACZ1187FB3F35C Connie Smith
TOP SIMILAR ARTIST: 6982 AR6XZ861187FB4CECD The Beatles